apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappybird
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flappybird
      env: prod
  template:
    metadata:
      labels:
        app: flappybird
        env: prod
    spec:
      containers:
      - image: bhargavbunny94/flappybird
        name: flappybird
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"

