apiVersion: v1
kind: Service
metadata:
  name: flappybird-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: flappybird
      env: prod
  type: LoadBalancer
